# Generated by Django 4.2.1 on 2024-01-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_photo_filename_alter_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='filename',
        ),
    ]
